global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          stack: eshop-nestjs
          compose_profile: dev
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
