{{- if .Values.databaseSecrets.create }}
{{- range $name, $sec := .Values.databaseSecrets.entries }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sec.secretName | default (printf "%s-db" $name) }}
  labels:
    {{- include "eshop-nestjs.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{ $sec.secretKey | default "databaseUrl" }}: {{ $sec.databaseUrl | default "postgresql://postgres:postgres@postgresql:5432/eshop_placeholder" | quote }}
{{- end }}
{{- end }}
