apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-nestjs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eshop
  source:
    repoURL: https://github.com/YOUR_ORG/eShopOnContainers-NestJS.git
    targetRevision: main
    path: deploy/helm/eshop-nestjs
    helm:
      releaseName: eshop
      valueFiles:
        - values.yaml
        - ../../gitops/environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: eshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /status
