apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eshop
  namespace: argocd
spec:
  description: eShop NestJS study stack
  sourceRepos:
    - https://github.com/YOUR_ORG/eShopOnContainers-NestJS.git
    - '*'
  destinations:
    - namespace: eshop
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
